method: grid
metric:
  name: val_acc
  goal: maximize
parameters:
  dataset:
    value: CIFAR100

  model:
    value: resnet50

  pretrained:
    value: true

  lr:
    values: [0.01]

  optimizer:
    value: SGD

  scheduler:
    value: ReduceLROnPlateau

  epochs:
    value: 100

  weight_decay:
    value: 0.0005

  num_workers:
    value: 2

  pin_memory:
    value: true

  use_amp:
    value: true

  use_wandb:
    value: true

  use_batch_size_scheduler:
    value: false
