method: grid
metric:
  name: val_acc
  goal: maximize
parameters:
  dataset:
    value: CIFAR100

  model:
    value: resnet18

  pretrained:
    value: false

  lr:
    value: 0.1

  optimizer:
    value: SGD

  scheduler:
    value: StepLR

  epochs:
    value: 50

  weight_decay:
    value: 0.0005

  num_workers:
    value: 2

  pin_memory:
    value: true

  use_amp:
    values: [false, true]

  use_wandb:
    value: true

  use_batch_size_scheduler:
    values: [false, true]
  
  use_compile:
    value: True